app <- ShinyDriver$new("../../", seed = 0)
app$snapshotInit("histo")

app$setInputs(xlab = "A TEST")
app$setInputs(breaks = 0)
app$snapshot()
app$setInputs(norm = TRUE)
app$snapshot()
app$setInputs(log = TRUE)
app$setInputs(breaks = 3.89)
app$snapshot()
