app <- ShinyDriver$new("../../", seed = 0)
app$snapshotInit("histo")

app$setInputs(xlab = "A ")
app$setInputs(xlab = "A TEST")
app$setInputs(breaks = 0.56)
app$setInputs(breaks = 0)
app$setInputs(breaks = 0.29)
app$setInputs(breaks = 0.24)
app$setInputs(breaks = 0)
app$setInputs(breaks = 5.76)
app$setInputs(breaks = 0)
app$snapshot()
app$setInputs(norm = TRUE)
app$snapshot()
app$setInputs(log = TRUE)
app$setInputs(breaks = 3.89)
app$snapshot()
app$snapshot()
