app <- ShinyDriver$new("../../", seed = 0)
app$snapshotInit("diversity")

app$snapshot()
app$setInputs(col = "2")
app$snapshot()
app$setInputs(col = "3")
app$snapshot()
app$setInputs(col = "4")
app$snapshot()
app$setInputs(rank = TRUE)
app$setInputs(col = "3")
app$snapshot()
app$setInputs(log = TRUE)
app$setInputs(plotType = "scatter")
app$snapshot()
app$setInputs(geom = TRUE)
app$snapshot()
app$setInputs(xlim = 36)
app$snapshot()
app$setInputs(plotType = "octave")
app$setInputs(geom = FALSE)
app$setInputs(norm = TRUE)
app$setInputs(col = "2")
app$setInputs(pngSize = 600)
app$snapshot()
app$setInputs(correct = TRUE)
app$snapshot()
